### ISSUE TITLE
Dependency Graph

### ISSUE THREAD

**Issue by sdiehl** [llvm-hs/llvm-hs-typed#2]
With regards to adding to a pretty printer for the typed AST there are two options:

* Make `llvm-hs-pretty` a dependency of `llvm-hs-typed` and then derive the pretty instances for the type tag constructors.
* Make llvm-hs-typed` a dependency of `llvm-hs-pretty` and derive instances for the tag constructors next to the main class definitions.

I don't think anybody but me uses this library yet, but just trying to plan if we want to coalesce projects someday.

**Comment by ollef** [comment]
As a datapoint Sixten uses `llvm-hs-pretty` but not `llvm-hs-typed` so we would probably prefer the first option to minimise dependencies. Not super important though. :)

**Comment by cocreature** [comment]
Yeah, I think at least for the foreseeable future it will be more common to use `llvm-hs-pretty` than it is to use `llvm-hs-typed`, so the first option seems more appealing.

**Comment by sdiehl** [comment]
Ok, I'll move forward with the first model.
